# Generated by Django 3.1.4 on 2021-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meokjeul', '0002_auto_20210110_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
