# Generated by Django 3.1.4 on 2021-01-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meokjeul', '0003_auto_20210111_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='coord_x',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='coord_y',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
