# Generated by Django 3.1.4 on 2021-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meokjeul', '0004_auto_20210115_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='coord_x',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='coord_y',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
